# Generated by Django 5.2 on 2026-04-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject'),
        ),
    ]
