# Generated by Django 5.2 on 2026-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_grade_options_alter_grade_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснение к оценке'),
        ),
    ]
