# Generated by Django 5.2 on 2026-04-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_grade_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выставления'),
        ),
    ]
