# Generated by Django 5.2 on 2026-04-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_alter_grade_date'),
        ('subjects', '0003_subject_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('current', 'Текущая оценка'), ('monthly', 'Месячная аттестация'), ('semester', 'Полугодовая сессия'), ('exam', 'Экзамен')], default='current', max_length=20, verbose_name='Тип оценки'),
        ),
        migrations.AddField(
            model_name='grade',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц аттестации'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полугодие'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(),
        ),
    ]
