# Generated by Django 5.2 on 2026-04-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер пары/урока')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='academic.teachingassignment', verbose_name='Назначение преподавателя')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'db_table': 'schedule',
                'ordering': ['day', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'day', 'start_time'), name='unique_assignment_day_start_time')],
            },
        ),
    ]
