# Generated by Django 5.2 on 2026-04-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='academic.teachingassignment', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'homework',
                'ordering': ['-created_at'],
            },
        ),
    ]
