# Generated by Django 5.2 on 2026-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
    ]
